on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 6'
name: build
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get git hash
      run: echo "${GITHUB_SHA}" > _build/hash.txt
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: false
        tags: |
          knaou/sphinx-plantuml:${{ github.sha }}
          knaou/sphinx-plantuml:latest
    - name: Start Docker Compose
      run: docker compose --project-directory e2e up
    - name: Archive build output
      if: env.ACTIONS_RUNTIME_TOKEN
      uses: actions/upload-artifact@v3
      with:
        name: build-report
        path: |
          !.gitignore
          _build/**/*
  build_and_push:
    runs-on: [ubuntu-latest]
    steps: 
    - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: knaou
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          knaou/sphinx-plantuml:latest

